/*
 * fcml_asm_errors.h
 *
 *  Created on: 10-05-2013
 *      Author: tAs
 */

#ifndef FCML_ASM_ERRORS_H_
#define FCML_ASM_ERRORS_H_

#include "fcml_ceh.h"

#define FCML_ERROR_CODE_BASE	FCML_CEH_USER_ERROR_CODE_BASE + 1250
#define FCML_WARN_CODE_BASE		FCML_CEH_USER_ERROR_CODE_BASE + 1500

// Errors.
enum fcml_en_asm_errors {
	FCML_EN_UNKNOWN_MNEMONIC = FCML_ERROR_CODE_BASE,
	FCML_EN_UNSUPPORTED_ADDRESSING_MODE = FCML_ERROR_CODE_BASE + 1,
	FCML_EN_UNSUPPORTED_OPPERAND = FCML_ERROR_CODE_BASE + 2,
	FCML_EN_UNSUPPORTED_OPPERAND_SIZE = FCML_ERROR_CODE_BASE + 3,
	FCML_EN_UNSUPPORTED_ADDRESS_SIZE = FCML_ERROR_CODE_BASE + 4,
	FCML_EN_RIP_DISPLACEMENT_NOT_SET = FCML_ERROR_CODE_BASE + 5,
	FCML_EN_UNSUPPORTED_ADDRESSING_FORM = FCML_ERROR_CODE_BASE + 6,
	FCML_EN_UNKNOWN_INSTRUCTION = FCML_ERROR_CODE_BASE + 7,
	FCML_EN_UNSUPPORTED_PREFIX = FCML_ERROR_CODE_BASE + 8,
	// AST.
	FCML_EN_APC_AST_ERROR_TO_MANY_OPERANDS = FCML_ERROR_CODE_BASE + 100,
	FCML_EN_APC_AST_ERROR_UNSUPPORTED_NODE_IN_EXPRESSION = FCML_ERROR_CODE_BASE + 101,
	FCML_EN_APC_AST_ERROR_DIVISION_BY_0 = FCML_ERROR_CODE_BASE + 102,
	FCML_EN_APC_AST_ERROR_WRONG_VALUE_FORMAT = FCML_ERROR_CODE_BASE + 103,
	FCML_EN_APC_AST_ERROR_VALUE_OUT_OF_RANGE = FCML_ERROR_CODE_BASE + 104,
	// parser/Lexer.
	FCML_EN_X64IP_ERROR_CAN_NOT_INITIALIZE_LEXER = FCML_ERROR_CODE_BASE + 200,
	FCML_EN_X64IP_ERROR_INVALID_SYNTAX  = FCML_ERROR_CODE_BASE + 201
};

// Warnings.
enum fcml_en_asm_warnings {
	FCML_EN_APC_AST_WARN_VALUE_OUT_OF_RANGE = FCML_WARN_CODE_BASE
};

#endif /* FCML_ASM_ERRORS_H_ */
