#line 2 "fcml_x64att_lexer.c"

#line 4 "fcml_x64att_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE att_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via att_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void att_restart (FILE *input_file ,yyscan_t yyscanner );
void att__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE att__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void att__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void att__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void att_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void att_pop_buffer_state (yyscan_t yyscanner );

static void att_ensure_buffer_stack (yyscan_t yyscanner );
static void att__load_buffer_state (yyscan_t yyscanner );
static void att__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER att__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE att__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE att__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE att__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *att_alloc (yy_size_t ,yyscan_t yyscanner );
void *att_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void att_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer att__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        att_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            att__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        att_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            att__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define att_wrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 160
#define YY_END_OF_BUFFER 161
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[253] =
    {   0,
      157,  157,  161,  158,  157,  159,  156,  158,  153,  154,
      149,  147,  146,  148,  145,  150,  158,  158,  155,  145,
      145,  145,  145,  145,  151,  152,  157,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  145,
        0,    1,  145,  145,  145,  145,  145,  145,    7,    3,
       23,   10,    6,   28,   26,    8,    4,    0,  133,   24,
        9,   30,    5,    0,  135,   25,    0,    0,    0,    0,
      132,  136,  137,    0,    0,   63,   64,    0,    0,    0,
        0,    0,   29,   27,  134,    0,    0,    0,    2,  145,
      145,  145,  140,  145,  145,   20,  119,  120,  121,  122,

      123,   22,  124,  125,  126,  127,  128,  129,  130,  131,
       39,   44,   42,   40,   46,   41,   45,   43,   71,   72,
       73,   74,   75,   76,   77,   78,   65,   66,   67,   68,
       69,   70,   47,   11,   31,   48,   12,   32,   55,   60,
       58,   56,   62,   57,   61,   59,   21,   19,    0,    0,
      111,  112,  113,  114,  115,  116,  117,  118,    0,    0,
      145,  138,  145,  140,  145,  140,  145,  145,   49,   13,
       33,   50,   14,   34,   51,   15,   35,   52,   16,   36,
       53,   17,   37,   54,   18,   38,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   79,   80,   81,   82,   83,

       84,   85,   86,   87,   88,   95,   96,   97,   98,   99,
      100,  101,  102,  103,  104,  145,  145,  139,  139,  145,
      145,    0,    0,    0,    0,    0,    0,    0,    0,   89,
       90,   91,   92,   93,   94,  105,  106,  107,  108,  109,
      110,  143,  145,  145,  145,  145,  145,  145,  144,  141,
      142,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    4,    5,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,    1,    1,
        1,    1,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   12,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   12,   45,   46,   47,   48,
       49,    1,   50,    1,   12,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   12,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   12,   71,   72,
       73,   74,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[75] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    3,    3,    3,    3,    3,    3,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        3,    3,    3,    3,    3,    3,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[255] =
    {   0,
        0,    0,  207,  542,  157,  542,  542,   50,  542,  542,
      542,  542,  542,  542,    0,  542,   36,  110,  542,   42,
       46,   47,   58,   94,  542,  542,   98,  102,  104,  112,
      153,  164,   46,   47,   54,  218,  113,   58,   59,    0,
        0,  233,  113,  113,  115,  103,  122,  122,  542,  542,
      542,  542,  542,  122,  542,  542,  542,  186,  542,  542,
      542,  136,  542,  247,  542,  542,  141,  159,  147,  163,
      240,  542,  542,  273,  266,  267,  268,  155,  258,  164,
      265,  267,  240,  272,  542,  329,  272,  274,    0,  277,
      281,  275,  322,  287,  317,  542,  542,  542,  542,  542,

      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  326,  327,  328,  329,
      330,  341,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  401,  409,
      542,  542,  542,  542,  542,  542,  542,  542,  417,  427,
      339,    0,  342,    0,  422,    0,  324,  350,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  464,   91,  221,  227,
      235,  318,  402,  406,  450,  542,  444,  542,  542,  542,

      542,  542,  542,  542,  542,  542,  457,  542,  542,  542,
      542,  542,  542,  542,  542,  432,  428,    0,    0,  434,
      443,  485,  493,  495,  496,  497,  499,  503,  505,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,    0,  461,  448,  466,  477,  482,  484,    0,    0,
        0,  542,  538,   96
    } ;

static yyconst flex_int16_t yy_def[255] =
    {   0,
      252,    1,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  253,  252,  252,  252,  252,  253,
      253,  253,  253,  253,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  253,
      254,  252,  253,  253,  253,  253,  253,  253,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  254,  253,
      253,  253,  253,  253,  253,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      253,  253,  253,  253,  253,  253,  253,  253,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  253,  253,  253,  253,  253,
      253,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,    0,  252,  252
    } ;

static yyconst flex_int16_t yy_nxt[617] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   19,   15,   20,   15,   15,   15,   15,
       15,   15,   15,   15,   21,   15,   22,   15,   15,   15,
       23,   15,   15,   15,   15,   24,   15,   15,   25,   26,
       15,   20,   15,   15,   15,   15,   15,   15,   15,   15,
       21,   15,   22,   15,   15,   15,   23,   15,   15,   15,
       15,   24,   15,   15,   28,   29,   30,   31,   32,   33,
       34,   41,   43,   44,   45,   35,   46,   72,   73,   74,
       36,   37,  222,   87,   88,   38,   39,  151,   89,   27,

       28,   29,   30,   31,   32,   33,   34,   41,   43,   44,
       45,   35,   46,   72,   73,   74,   36,   37,   47,   87,
       88,   38,   39,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   49,   48,   52,   50,   90,   53,   91,
       92,   93,   54,   56,   47,   83,   57,   51,   94,   55,
       95,   84,   58,   59,   85,   86,   96,   60,   27,   49,
       48,   52,   50,   90,   53,   91,   92,   93,   54,   56,
      102,   83,   57,   51,   94,   55,   95,   84,   58,   59,
       85,   86,   96,   60,   61,   62,  111,   63,   67,   68,
       69,   70,  114,   64,   65,  115,  102,  112,   66,   97,

      139,   98,   99,  100,  113,   71,  252,  101,  116,  142,
       61,   62,  111,   63,   67,   68,   69,   70,  114,   64,
       65,  115,  223,  112,   66,  252,  139,  152,  224,  252,
      113,   71,   75,  153,  116,  142,  225,  252,  252,   76,
       77,  154,   78,   79,   80,   81,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,  252,  252,  252,   82,
      103,  104,  105,  106,  107,  108,  109,  110,   78,   79,
       80,   81,  117,  252,  147,  252,  252,  252,  118,  127,
      128,  129,  130,  131,  132,   82,  119,  120,  121,  122,
      123,  124,  125,  126,  133,  136,  140,  143,  117,  145,

      147,  134,  137,  141,  118,  146,  148,  159,  252,  160,
      144,  135,  138,  161,  162,  163,  252,  252,  252,  226,
      133,  136,  140,  143,  155,  145,  167,  134,  137,  141,
      149,  146,  148,  159,  150,  160,  144,  135,  138,  161,
      162,  163,  151,  152,  153,  154,  155,  156,  157,  158,
      164,  168,  167,  169,  172,  175,  178,  181,  165,  252,
      170,  173,  176,  179,  182,  216,  217,  220,  184,  166,
      171,  174,  177,  180,  183,  185,  164,  168,  221,  169,
      172,  175,  178,  181,  165,  186,  170,  173,  176,  179,
      182,  216,  217,  220,  184,  166,  171,  174,  177,  180,

      183,  185,  149,  227,  221,  252,  150,  228,  156,  252,
      187,  186,  157,  252,  151,  152,  153,  154,  155,  156,
      157,  158,  188,  189,  190,  191,  192,  193,  194,  195,
      196,  197,  198,  199,  200,  201,  202,  203,  204,  205,
      206,  207,  208,  209,  210,  211,  212,  213,  214,  215,
      218,  229,  252,  252,  252,  252,  158,  230,  231,  232,
      233,  234,  235,  242,  243,  187,  244,  245,  252,  219,
      236,  237,  238,  239,  240,  241,  218,  188,  189,  190,
      191,  192,  193,  194,  195,  252,  222,  246,  247,  242,
      243,  151,  244,  245,  223,  219,  224,  225,  226,  152,

      227,  153,  154,  155,  228,  156,  229,  248,  249,  157,
      250,  158,  251,  246,  247,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  248,  249,  252,  250,  252,  251,   40,
       40,    3,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252
    } ;

static yyconst flex_int16_t yy_chk[617] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    8,    8,    8,    8,    8,
        8,   17,   20,   21,   22,    8,   23,   33,   34,   35,
        8,    8,  188,   38,   39,    8,    8,  188,  254,   27,

        8,    8,    8,    8,    8,    8,    8,   17,   20,   21,
       22,    8,   23,   33,   34,   35,    8,    8,   24,   38,
       39,    8,    8,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   28,   24,   29,   28,   43,   29,   44,
       45,   46,   29,   30,   24,   37,   30,   28,   47,   29,
       48,   37,   30,   30,   37,   37,   54,   30,    5,   28,
       24,   29,   28,   43,   29,   44,   45,   46,   29,   30,
       62,   37,   30,   28,   47,   29,   48,   37,   30,   30,
       37,   37,   54,   30,   31,   31,   67,   31,   32,   32,
       32,   32,   69,   31,   31,   70,   62,   68,   31,   58,

       78,   58,   58,   58,   68,   32,    3,   58,   70,   80,
       31,   31,   67,   31,   32,   32,   32,   32,   69,   31,
       31,   70,  189,   68,   31,    0,   78,  189,  190,    0,
       68,   32,   36,  190,   70,   80,  191,    0,    0,   36,
       36,  191,   36,   36,   36,   36,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,    0,    0,    0,   36,
       64,   64,   64,   64,   64,   64,   64,   64,   36,   36,
       36,   36,   71,    0,   83,    0,    0,    0,   71,   75,
       75,   75,   75,   75,   75,   36,   74,   74,   74,   74,
       74,   74,   74,   74,   76,   77,   79,   81,   71,   82,

       83,   76,   77,   79,   71,   82,   84,   87,    0,   88,
       81,   76,   77,   90,   91,   92,    0,    0,    0,  192,
       76,   77,   79,   81,  192,   82,   94,   76,   77,   79,
       86,   82,   84,   87,   86,   88,   81,   76,   77,   90,
       91,   92,   86,   86,   86,   86,   86,   86,   86,   86,
       93,   95,   94,  127,  128,  129,  130,  131,   93,    0,
      127,  128,  129,  130,  131,  161,  163,  167,  132,   93,
      127,  128,  129,  130,  131,  132,   93,   95,  168,  127,
      128,  129,  130,  131,   93,  132,  127,  128,  129,  130,
      131,  161,  163,  167,  132,   93,  127,  128,  129,  130,

      131,  132,  149,  193,  168,    0,  149,  194,  193,    0,
      150,  132,  194,    0,  149,  149,  149,  149,  149,  149,
      149,  149,  150,  150,  150,  150,  150,  150,  150,  150,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      165,  195,    0,    0,    0,    0,  195,  197,  197,  197,
      197,  197,  197,  216,  217,  187,  220,  221,    0,  165,
      207,  207,  207,  207,  207,  207,  165,  187,  187,  187,
      187,  187,  187,  187,  187,    0,  222,  243,  244,  216,
      217,  222,  220,  221,  223,  165,  224,  225,  226,  223,

      227,  224,  225,  226,  228,  227,  229,  245,  246,  228,
      247,  229,  248,  243,  244,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  245,  246,    0,  247,    0,  248,  253,
      253,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "fcml_x64att_lexer.lex"
#line 2 "fcml_x64att_lexer.lex"
	#include <stdio.h>
	#include <stdlib.h>
	
	#include "fcml_common_lex.h"
	#include "fcml_x64att_parser.tab.h"
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
/*White spaces.*/
#line 664 "fcml_x64att_lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE struct fcml_st_parser_data *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int att_lex_init (yyscan_t* scanner);

int att_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int att_lex_destroy (yyscan_t yyscanner );

int att_get_debug (yyscan_t yyscanner );

void att_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE att_get_extra (yyscan_t yyscanner );

void att_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *att_get_in (yyscan_t yyscanner );

void att_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *att_get_out (yyscan_t yyscanner );

void att_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t att_get_leng (yyscan_t yyscanner );

char *att_get_text (yyscan_t yyscanner );

int att_get_lineno (yyscan_t yyscanner );

void att_set_lineno (int line_number ,yyscan_t yyscanner );

int att_get_column  (yyscan_t yyscanner );

void att_set_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * att_get_lval (yyscan_t yyscanner );

void att_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int att_wrap (yyscan_t yyscanner );
#else
extern int att_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int att_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int att_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 29 "fcml_x64att_lexer.lex"


 /*Decimal integers.*/
#line 901 "fcml_x64att_lexer.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			att_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				att__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		att__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 252 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "fcml_x64att_lexer.lex"
{ return fcml_fn_pu_parse_integer( yytext, &(yylval->integer_value), 10 ); }
	YY_BREAK
/*HEX integers.*/
case 2:
YY_RULE_SETUP
#line 35 "fcml_x64att_lexer.lex"
{ return fcml_fn_pu_parse_integer( yytext, &(yylval->integer_value), 16 ); }
	YY_BREAK
/*GPR.*/
case 3:
YY_RULE_SETUP
#line 38 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_AL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_CL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_DL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_BL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_AH); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_CH); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_DH); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_BH); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R8L); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R9L); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R10L); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R11L); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R12L); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R13L); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R14L); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_REG(FCML_REG_R15L); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_X_REG(FCML_REG_SPL); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_X_REG(FCML_REG_BPL); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_X_REG(FCML_REG_SIL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_8_X_REG(FCML_REG_DIL); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_AX); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_CX); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_DX); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_BX); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_SP); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_BP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_SI); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_DI); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R8W); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R9W); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R10W); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R11W); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R12W); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R13W); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R14W); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_16_REG(FCML_REG_R15W); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_EAX); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_ECX); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_EDX); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_EBX); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_ESP); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_EBP); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_ESI); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_EDI); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R8D); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R9D); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R10D); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R11D); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R12D); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R13D); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R14D); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_32_REG(FCML_REG_R15D); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RAX); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RCX); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RDX); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RBX); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RSP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RBP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RSI); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_RDI); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R8); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R9); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R10); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R11); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R12); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R13); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R14); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "fcml_x64att_lexer.lex"
{ return FCML_FM_GPRS_64_REG(FCML_REG_R15); }
	YY_BREAK
/*SIMD-MMX*/
case 71:
YY_RULE_SETUP
#line 112 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM0); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM1); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM2); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM3); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM4); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM5); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM6); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_64_REG(FCML_REG_MM7); }
	YY_BREAK
/*SIMD-XMM*/
case 79:
YY_RULE_SETUP
#line 122 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM0); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM1); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM2); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM3); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM4); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM5); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM6); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM7); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM8); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM9); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM10); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM11); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 134 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM12); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 135 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM13); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 136 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM14); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_128_REG(FCML_REG_XMM15); }
	YY_BREAK
/*SIMD-YMM*/
case 95:
YY_RULE_SETUP
#line 140 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM0); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM1); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM2); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM3); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM4); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM5); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM6); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM7); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM8); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 149 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM9); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 150 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM10); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 151 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM11); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM12); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM13); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM14); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 155 "fcml_x64att_lexer.lex"
{ return FCML_FM_SIMD_256_REG(FCML_REG_YMM15); }
	YY_BREAK
/*FPU*/
case 111:
YY_RULE_SETUP
#line 158 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST0); }				
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 159 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST1); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 160 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST2); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 161 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST3); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 162 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST4); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 163 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST5); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 164 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST6); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 165 "fcml_x64att_lexer.lex"
{ return FCML_FM_FPU_REG(FCML_REG_ST7); }
	YY_BREAK
/*Control registers.*/
case 119:
YY_RULE_SETUP
#line 168 "fcml_x64att_lexer.lex"
{ return FCML_FM_CR_REG(FCML_REG_CR0); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 169 "fcml_x64att_lexer.lex"
{ return FCML_FM_CR_REG(FCML_REG_CR2); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 170 "fcml_x64att_lexer.lex"
{ return FCML_FM_CR_REG(FCML_REG_CR3); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 171 "fcml_x64att_lexer.lex"
{ return FCML_FM_CR_REG(FCML_REG_CR4); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 172 "fcml_x64att_lexer.lex"
{ return FCML_FM_CR_REG(FCML_REG_CR8); }
	YY_BREAK
/*Debug registers.*/
case 124:
YY_RULE_SETUP
#line 175 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR0); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 176 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR1); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 177 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR2); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 178 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR3); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 179 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR4); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 180 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR5); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 181 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR6); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 182 "fcml_x64att_lexer.lex"
{ return FCML_FM_DR_REG(FCML_REG_DR7); }
	YY_BREAK
/*Segment registers.*/
case 132:
YY_RULE_SETUP
#line 185 "fcml_x64att_lexer.lex"
{ return FCML_FM_SEG_REG(FCML_REG_ES); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 186 "fcml_x64att_lexer.lex"
{ return FCML_FM_SEG_REG(FCML_REG_CS); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 187 "fcml_x64att_lexer.lex"
{ return FCML_FM_SEG_REG(FCML_REG_SS); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 188 "fcml_x64att_lexer.lex"
{ return FCML_FM_SEG_REG(FCML_REG_DS); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 189 "fcml_x64att_lexer.lex"
{ return FCML_FM_SEG_REG(FCML_REG_FS); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 190 "fcml_x64att_lexer.lex"
{ return FCML_FM_SEG_REG(FCML_REG_GS); }
	YY_BREAK
/* Prefixes */
case 138:
YY_RULE_SETUP
#line 194 "fcml_x64att_lexer.lex"
{
					yylval->prefixes = FCML_PREFIX_LOCK;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 199 "fcml_x64att_lexer.lex"
{
					yylval->prefixes = FCML_PREFIX_REPNE;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 204 "fcml_x64att_lexer.lex"
{
					yylval->prefixes = FCML_PREFIX_REPE;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 209 "fcml_x64att_lexer.lex"
{
					yylval->prefixes = FCML_PREFIX_XACQUIRE;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 214 "fcml_x64att_lexer.lex"
{
					yylval->prefixes = FCML_PREFIX_XRELEASE;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 219 "fcml_x64att_lexer.lex"
{
					yylval->hints = FCML_PREFIX_BRANCH_HINT;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 224 "fcml_x64att_lexer.lex"
{
					yylval->hints = FCML_PREFIX_NOBRANCH_HINT;
					return FCML_TK_PREFIX;
				}
	YY_BREAK
/* Identifiers. */
case 145:
YY_RULE_SETUP
#line 230 "fcml_x64att_lexer.lex"
{
					yylval->symbol.text = (fcml_string)yytext;
					yylval->symbol.length = yyleng;
					return FCML_TK_SYMBOL; 
				}
	YY_BREAK
/* Operators and parentheses. */
case 146:
YY_RULE_SETUP
#line 237 "fcml_x64att_lexer.lex"
{ return ','; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 238 "fcml_x64att_lexer.lex"
{ return '+'; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 239 "fcml_x64att_lexer.lex"
{ return '-'; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 240 "fcml_x64att_lexer.lex"
{ return '*'; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 241 "fcml_x64att_lexer.lex"
{ return '/'; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 242 "fcml_x64att_lexer.lex"
{ return '['; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 243 "fcml_x64att_lexer.lex"
{ return ']'; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 244 "fcml_x64att_lexer.lex"
{ return '('; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 245 "fcml_x64att_lexer.lex"
{ return ')'; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 246 "fcml_x64att_lexer.lex"
{ return ':'; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 247 "fcml_x64att_lexer.lex"
{ return '$'; }
	YY_BREAK
/* Ignore white spaces. */
case 157:
YY_RULE_SETUP
#line 250 "fcml_x64att_lexer.lex"

	YY_BREAK
/*Anything else is not expected.*/
case 158:
YY_RULE_SETUP
#line 253 "fcml_x64att_lexer.lex"
{ return FCML_TK_UNEXPECTED; }
	YY_BREAK
/*Ignore like white spaces.*/
case 159:
/* rule 159 can match eol */
YY_RULE_SETUP
#line 256 "fcml_x64att_lexer.lex"

	YY_BREAK
case 160:
YY_RULE_SETUP
#line 258 "fcml_x64att_lexer.lex"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1823 "fcml_x64att_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * att_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( att_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of att_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					att_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			att_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) att_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 252);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					att_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( att_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void att_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        att_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            att__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	att__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	att__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void att__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		att_pop_buffer_state();
	 *		att_push_buffer_state(new_buffer);
     */
	att_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	att__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (att_wrap()) processing, but the only time this flag
	 * is looked at is after att_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void att__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE att__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) att_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in att__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) att_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in att__create_buffer()" );

	b->yy_is_our_buffer = 1;

	att__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with att__create_buffer()
 * @param yyscanner The scanner object.
 */
    void att__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		att_free((void *) b->yy_ch_buf ,yyscanner );

	att_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a att_restart() or at EOF.
 */
    static void att__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	att__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then att__init_buffer was _probably_
     * called from att_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void att__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		att__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void att_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	att_ensure_buffer_stack(yyscanner);

	/* This block is copied from att__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from att__switch_to_buffer. */
	att__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void att_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	att__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		att__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void att_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)att_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in att_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)att_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in att_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE att__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) att_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in att__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	att__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to att_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       att__scan_bytes() instead.
 */
YY_BUFFER_STATE att__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return att__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to att_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE att__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) att_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in att__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = att__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in att__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE att_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int att_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int att_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *att_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *att_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t att_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *att_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void att_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void att_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "att_set_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void att_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "att_set_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see att__switch_to_buffer
 */
void att_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void att_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int att_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void att_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * att_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void att_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* att_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int att_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) att_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* att_lex_init_extra has the same functionality as att_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to att_alloc in
 * the yyextra field.
 */

int att_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    att_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) att_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    att_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from att_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * att_lex_init()
     */
    return 0;
}

/* att_lex_destroy is for both reentrant and non-reentrant scanners. */
int att_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		att__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		att_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	att_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        att_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * att_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    att_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *att_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *att_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void att_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see att_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 258 "fcml_x64att_lexer.lex"




