jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: |
          apt-get update -qq
          apt-get install build-essential autoconf libtool-bin flex bison git -y
      - checkout
      - run: |
          autoreconf -i
          ./configure
          make && make check
