#line 2 "fcml_intel_lexer.c"

#line 4 "fcml_intel_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE intel_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via intel_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void intel_restart (FILE *input_file ,yyscan_t yyscanner );
void intel__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE intel__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void intel__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void intel__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void intel_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void intel_pop_buffer_state (yyscan_t yyscanner );

static void intel_ensure_buffer_stack (yyscan_t yyscanner );
static void intel__load_buffer_state (yyscan_t yyscanner );
static void intel__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER intel__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE intel__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE intel__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE intel__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *intel_alloc (yy_size_t ,yyscan_t yyscanner );
void *intel_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void intel_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer intel__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        intel_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            intel__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        intel_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            intel__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define intel_wrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 185
#define YY_END_OF_BUFFER 186
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[446] =
    {   0,
      182,  182,  186,  183,  182,  184,  179,  180,  175,  173,
      172,  174,  176,    1,    1,    1,    1,    1,  181,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      177,  178,  182,    1,    0,    1,    4,    0,    1,    1,
        0,    1,    1,    1,  171,  171,    9,    5,   25,   12,
        8,   30,  171,   28,  171,   10,    6,  171,  135,   26,
       11,   32,    7,  171,  171,  137,  171,   27,  171,  171,
      171,  171,  134,  171,  138,  171,  139,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,   65,   66,  171,

      171,  171,  171,  171,  171,  171,   31,   29,  136,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,    0,
        2,    1,    0,    0,    0,  169,   22,  171,  171,  121,
      122,  123,  124,  125,   24,  171,  171,  126,  127,  128,
      129,  130,  131,  132,  133,  171,   41,   46,   44,   42,
       48,   43,   47,   45,  163,  171,  171,  171,  171,   73,
       74,   75,   76,   77,   78,   79,   80,  171,  171,  171,
      171,  171,  171,  171,   67,   68,   69,   70,   71,   72,
       49,   13,   33,   50,   14,   34,   57,   62,   60,   58,
       64,   59,  168,  158,  140,   63,   61,  170,   23,   21,

        0,    0,  113,  114,  115,  116,  117,  118,  119,  120,
      171,  171,  171,  171,  171,  171,  171,  171,  171,    3,
        0,    0,    0,    0,  171,  141,  171,  171,  171,  171,
      171,  156,  171,  171,  164,  171,  171,  171,  171,  171,
       51,   15,   35,   52,   16,   36,   53,   17,   37,   54,
       18,   38,   55,   19,   39,   56,   20,   40,  158,  171,
      158,  113,  114,  115,  116,  117,  118,  119,  120,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  171,  171,
      142,  171,   81,   82,   83,   84,   85,   86,   87,   88,
       89,   90,  171,  171,  171,   97,   98,   99,  100,  101,

      102,  103,  104,  105,  106,  171,  171,    0,    0,    0,
        0,  171,    0,  171,  171,  143,  144,  171,  171,  171,
      171,  147,  144,  171,  145,  157,  157,    0,    0,    0,
        0,    0,    0,    0,    0,  146,  146,    0,  171,   91,
       92,   93,   94,   95,   96,  171,  171,  150,  107,  108,
      109,  110,  111,  112,  171,  151,    0,  152,  153,  154,
      161,    0,  167,  147,    0,    0,  171,  171,  149,  171,
        0,  148,    0,    0,    0,  171,  171,  171,    0,  171,
        0,  155,    0,    0,    0,    0,    0,    0,  171,  171,
        0,  171,    0,    0,    0,    0,    0,  171,  150,  171,

        0,  151,    0,    0,    0,    0,    0,  141,    0,    0,
      166,  171,    0,  162,    0,    0,    0,    0,  142,  159,
      160,    0,    0,    0,    0,    0,    0,  143,  144,  165,
        0,  147,    0,  145,  146,  150,  151,    0,  152,  153,
      154,  149,  148,  155,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,    1,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,    1,    1,
        1,    1,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   32,   44,   45,   46,   47,
       48,    1,   49,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   32,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   32,   71,   72,
       73,   74,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[75] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    2,    2,    2,    2,    2,    2,    3,    4,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    3,
        2,    2,    2,    2,    2,    2,    3,    4,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[449] =
    {   0,
        0,    0,  352,  955,   73,  955,  955,  955,  955,  955,
      955,  955,  955,   66,  127,   83,   85,   86,  955,  132,
      175,  130,  219,  203,   65,   59,    0,   68,   68,   72,
      131,   64,   66,  128,  279,  276,  172,  112,  302,  130,
      955,  955,  110,  113,  129,  131,  955,    0,  191,  194,
      362,    0,  249,  260,    0,  132,    0,    0,    0,    0,
        0,  174,  194,    0,  170,    0,    0,  254,    0,    0,
        0,  248,    0,  170,  342,    0,  188,    0,  217,  278,
      222,  252,  332,  241,    0,  258,    0,  197,  359,  386,
      270,  274,  276,  302,  318,  328,  394,  387,  389,  322,

      379,  342,  387,  391,  355,  388,  403,  400,    0,  461,
      389,  403,  402,  343,  410,  427,  431,  435,  434,  451,
        0,  472,  437,  439,  440,    0,    0,  451,  462,    0,
        0,    0,    0,    0,    0,  463,  455,    0,    0,    0,
        0,    0,    0,    0,    0,  453,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  454,  468,  468,  473,    0,
        0,    0,    0,    0,    0,    0,    0,  467,  465,  466,
      467,  468,  474,  475,  503,  514,  515,  517,  518,  519,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  555,    0,    0,    0,    0,    0,    0,

      607,  626,    0,    0,    0,    0,    0,    0,    0,    0,
      481,  499,  500,  517,  634,  526,  525,  694,  527,  955,
      524,  535,  539,  558,  578,  347,  580,  567,  606,  609,
      597,    0,  299,  616,    0,  634,  632,  633,  621,  636,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  642,
        0,  955,  955,  955,  955,  955,  955,  955,  955,  715,
      124,  228,  611,  664,  669,  670,  675,  678,  638,  641,
      344,  648,    0,  686,    0,    0,    0,    0,    0,    0,
        0,    0,  657,  665,  670,    0,  727,    0,    0,    0,

        0,    0,    0,    0,    0,  685,  697,  683,  699,  708,
      709,  715,  709,  706,  724,  332,  325,  726,  727,  730,
      722,  324,  323,  733,  315,    0,    0,  764,  765,  784,
      787,  790,  793,  796,  799,  292,  275,  739,  748,    0,
        0,    0,    0,    0,    0,  742,  757,  271,    0,    0,
        0,    0,    0,    0,  766,  234,  783,  233,  227,  218,
        0,  770,    0,  215,  775,  776,  790,  780,  165,  793,
      782,  159,  783,  784,  781,  784,  799,  786,  790,  803,
      793,  119,  794,  796,  797,  796,  795,  800,  803,  812,
      818,  830,  823,  828,  825,  826,  830,  844,  111,  846,

      833,  109,  834,  839,  836,  838,  839,  955,  842,  844,
        0,  850,  844,    0,  847,  847,  850,  851,  955,    0,
        0,  856,  858,  858,  866,  870,  875,  955,  955,    0,
      879,  955,  880,  955,  955,  955,  955,  881,  955,  955,
      955,  955,  955,  955,  955,  947,  950,   74
    } ;

static yyconst flex_int16_t yy_def[449] =
    {   0,
      445,    1,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,   15,   15,   15,  445,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      445,  445,  445,   15,  447,  447,  445,  448,   15,   15,
       15,   51,   15,   15,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  447,
      448,   15,   51,   51,   51,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      445,  445,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  445,
       51,  445,  445,  445,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  445,  445,  445,
      445,  446,  445,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  445,  445,  445,
      445,  445,  445,  445,  445,  446,  446,  445,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  445,  445,  445,  445,
      446,  445,  446,  446,  445,  445,  446,  446,  446,  446,
      445,  446,  445,  445,  445,  446,  446,  446,  445,  446,
      445,  445,  445,  445,  445,  445,  445,  445,  446,  446,
      445,  446,  445,  445,  445,  445,  445,  446,  446,  446,

      445,  446,  445,  445,  445,  445,  445,  445,  445,  445,
      446,  446,  445,  446,  445,  445,  445,  445,  445,  446,
      446,  445,  445,  445,  445,  445,  445,  445,  445,  446,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,    0,  445,  445,  445
    } ;

static yyconst flex_int16_t yy_nxt[1030] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   17,   17,   17,   17,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   27,   27,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   27,   38,   39,   40,   27,   41,   42,   27,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   27,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   27,
       38,   39,   40,   27,   43,  121,   43,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   84,   45,   45,
       45,   46,   45,   45,   44,   47,   44,   44,   44,   87,

       44,   54,   53,   88,   89,   85,   90,   93,   86,   94,
       48,   43,  381,   43,  379,   84,   45,   45,   45,   46,
       45,   45,  404,   47,   44,  328,   87,  328,   44,  262,
       88,   89,   85,   90,   93,   86,   94,   48,   49,   44,
       44,   44,   50,   44,   44,   44,   44,   44,  113,   51,
       51,   51,   52,   51,   51,   56,   47,   91,   47,   66,
       47,   57,  394,   67,  118,   58,   95,   92,  391,   68,
       69,   96,  126,  119,   70,  113,   59,   51,   51,   51,
       52,   51,   51,   56,   47,   91,   47,   66,   47,   57,
       67,  118,   58,   95,   92,  111,   68,   69,   96,  126,

      119,   70,   44,   59,   60,   44,   44,  127,   61,   44,
      122,  129,   62,  137,   63,  112,  128,  123,  371,   64,
       65,  385,  157,  111,  146,   79,   80,   81,   82,  329,
      384,  329,   60,  263,  127,   61,  383,  381,  129,   62,
      137,   63,  112,   83,  128,  123,   64,   65,   71,   72,
      157,  146,   73,   79,   80,   81,   82,   74,   75,   76,
       44,  147,   77,   78,   44,  130,  150,  131,  132,  133,
       83,   44,  124,  134,  379,   44,   71,   72,  374,   73,
      155,  135,  151,  125,   74,   75,   76,  136,  147,   77,
       78,   97,  169,  150,  156,  374,  152,  170,   98,   99,

      124,  100,  101,  102,  103,  104,  107,  155,  135,  105,
      151,  125,  171,  108,  136,  148,  109,  110,  373,  106,
      169,  156,  149,  152,  114,  170,  366,  371,  366,  100,
      101,  102,  103,  104,  107,  365,  115,  105,  172,  171,
      108,  116,  148,  109,  110,  117,  106,  338,  319,  149,
      313,  445,  114,  138,  139,  140,  141,  142,  143,  144,
      145,  173,  153,  115,  174,  172,  187,  214,  116,  154,
      445,  445,  117,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,  158,  445,  445,  190,   51,  173,  445,
      153,  174,  195,  187,  159,  214,  154,  160,  161,  162,

      163,  164,  165,  166,  167,  175,  176,  177,  178,  179,
      180,  158,  181,  190,  184,   51,  188,  191,  196,  195,
      182,  159,  185,  189,  193,  197,  198,  445,  194,  168,
      183,  192,  186,  200,  211,  445,  199,  445,  445,  212,
      181,  213,  184,  188,  215,  191,  196,  182,  445,  185,
      189,  193,  197,  216,  198,  194,  168,  183,  192,  186,
      200,  211,  201,  199,  201,  202,  212,  217,  213,  218,
      219,  215,  203,  204,  205,  206,  207,  208,  209,  210,
      220,  216,  222,   44,  223,  224,  225,   44,  226,  227,
      445,  228,  229,  230,  217,  221,  218,  219,  231,  445,

      232,  233,  445,  234,  235,  236,  237,  238,  220,  222,
      239,  223,  224,  225,  240,  445,  226,  227,  228,  229,
      230,  445,  279,  221,  445,  281,  231,  232,  241,  233,
      234,  235,  236,  237,  238,  445,  242,  239,  280,  244,
      247,  240,  250,  253,  256,  445,  243,  245,  248,  279,
      251,  254,  257,  281,  445,  282,  241,  246,  249,  294,
      252,  255,  258,  242,  295,  280,  307,  244,  247,  308,
      250,  253,  256,  243,  245,  248,  309,  251,  254,  257,
      310,  259,  282,  445,  246,  249,  294,  252,  255,  258,
      260,  295,  445,  307,  445,  445,  308,  445,  445,  311,

      445,  261,  312,  309,  314,  445,  315,  310,  201,  259,
      201,  202,  330,  445,  330,  445,  264,  260,  262,  263,
      264,  265,  266,  267,  268,  269,  311,  270,  261,  270,
      312,  316,  314,  315,  317,  445,  318,  271,  272,  273,
      274,  275,  276,  277,  278,  283,  284,  285,  286,  287,
      288,  289,  290,  291,  292,  320,  321,  322,  323,  316,
      324,  325,  317,  318,  336,  331,  337,  331,  326,  265,
      332,  333,  332,  333,  266,  267,  334,  293,  334,  335,
      268,  335,  320,  269,  321,  322,  323,  324,  327,  325,
      339,  347,  336,  346,  337,  348,  326,  340,  341,  342,

      343,  344,  345,  445,  293,  296,  297,  298,  299,  300,
      301,  302,  303,  304,  305,  327,  270,  339,  270,  347,
      346,  355,  356,  348,  357,  358,  271,  272,  273,  274,
      275,  276,  277,  278,  359,  360,  445,  306,  349,  350,
      351,  352,  353,  354,  361,  445,  362,  363,  355,  364,
      356,  357,  367,  358,  368,  369,  445,  370,  372,  445,
      445,  445,  359,  360,  306,  328,  329,  328,  329,  262,
      263,  445,  361,  362,  363,  445,  375,  364,  376,  378,
      367,  377,  368,  369,  370,  330,  372,  330,  331,  264,
      331,  332,  265,  332,  333,  266,  333,  334,  267,  334,

      335,  268,  335,  375,  269,  380,  376,  378,  377,  382,
      445,  386,  387,  388,  389,  445,  390,  392,  445,  393,
      395,  396,  397,  398,  399,  445,  400,  401,  402,  445,
      403,  405,  380,  406,  407,  408,  409,  382,  386,  387,
      388,  410,  389,  390,  411,  392,  393,  395,  396,  397,
      398,  412,  399,  400,  401,  413,  402,  403,  405,  414,
      406,  407,  408,  409,  415,  416,  417,  418,  410,  419,
      420,  411,  421,  445,  422,  423,  424,  425,  412,  426,
      427,  428,  413,  429,  430,  431,  432,  414,  433,  434,
      435,  415,  416,  417,  418,  436,  419,  437,  420,  438,

      421,  422,  423,  424,  425,  439,  426,  427,  428,  440,
      429,  430,  431,  432,  441,  433,  434,  435,  442,  443,
      444,  445,  436,  445,  437,  445,  438,  445,  445,  445,
      445,  445,  439,  445,  445,  445,  440,  445,  445,  445,
      445,  441,  445,  445,  445,  442,  443,  444,   55,   55,
       55,  120,  445,  120,    3,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445
    } ;

static yyconst flex_int16_t yy_chk[1030] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,  448,    5,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   25,   14,   14,
       14,   14,   14,   14,   16,   14,   17,   18,   16,   26,

       17,   18,   16,   28,   29,   25,   30,   32,   25,   33,
       14,   43,  402,   43,  399,   25,   14,   14,   14,   14,
       14,   14,  382,   14,   44,  271,   26,  271,   44,  271,
       28,   29,   25,   30,   32,   25,   33,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   38,   15,
       15,   15,   15,   15,   15,   20,   15,   31,   45,   22,
       46,   20,  372,   22,   40,   20,   34,   31,  369,   22,
       22,   34,   56,   40,   22,   38,   20,   15,   15,   15,
       15,   15,   15,   20,   15,   31,   45,   22,   46,   20,
       22,   40,   20,   34,   31,   37,   22,   22,   34,   56,

       40,   22,   49,   20,   21,   50,   49,   62,   21,   50,
       49,   65,   21,   74,   21,   37,   63,   50,  364,   21,
       21,  360,   88,   37,   77,   24,   24,   24,   24,  272,
      359,  272,   21,  272,   62,   21,  358,  356,   65,   21,
       74,   21,   37,   24,   63,   50,   21,   21,   23,   23,
       88,   77,   23,   24,   24,   24,   24,   23,   23,   23,
       53,   79,   23,   23,   53,   68,   81,   68,   68,   68,
       24,   54,   53,   68,  348,   54,   23,   23,  337,   23,
       84,   72,   82,   54,   23,   23,   23,   72,   79,   23,
       23,   35,   91,   81,   86,  336,   82,   92,   35,   35,

       53,   35,   35,   35,   35,   35,   36,   84,   72,   35,
       82,   54,   93,   36,   72,   80,   36,   36,  325,   35,
       91,   86,   80,   82,   39,   92,  323,  322,  317,   35,
       35,   35,   35,   35,   36,  316,   39,   35,   94,   93,
       36,   39,   80,   36,   36,   39,   35,  281,  233,   80,
      226,    3,   39,   75,   75,   75,   75,   75,   75,   75,
       75,   95,   83,   39,   96,   94,  100,  114,   39,   83,
        0,    0,   39,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   89,    0,    0,  102,   51,   95,    0,
       83,   96,  105,  100,   89,  114,   83,   90,   90,   90,

       90,   90,   90,   90,   90,   97,   97,   97,   97,   97,
       97,   89,   98,  102,   99,   51,  101,  103,  106,  105,
       98,   89,   99,  101,  104,  106,  107,    0,  104,   90,
       98,  103,   99,  108,  111,    0,  107,    0,    0,  112,
       98,  113,   99,  101,  115,  103,  106,   98,    0,   99,
      101,  104,  106,  116,  107,  104,   90,   98,  103,   99,
      108,  111,  110,  107,  110,  110,  112,  117,  113,  118,
      119,  115,  110,  110,  110,  110,  110,  110,  110,  110,
      120,  116,  123,  122,  124,  125,  128,  122,  129,  136,
        0,  137,  146,  156,  117,  122,  118,  119,  157,    0,

      158,  159,    0,  168,  169,  170,  171,  172,  120,  123,
      173,  124,  125,  128,  174,    0,  129,  136,  137,  146,
      156,    0,  211,  122,    0,  213,  157,  158,  175,  159,
      168,  169,  170,  171,  172,    0,  175,  173,  212,  176,
      177,  174,  178,  179,  180,    0,  175,  176,  177,  211,
      178,  179,  180,  213,    0,  214,  175,  176,  177,  216,
      178,  179,  180,  175,  217,  212,  219,  176,  177,  221,
      178,  179,  180,  175,  176,  177,  222,  178,  179,  180,
      223,  194,  214,    0,  176,  177,  216,  178,  179,  180,
      194,  217,    0,  219,    0,    0,  221,    0,    0,  224,

        0,  194,  225,  222,  227,    0,  228,  223,  201,  194,
      201,  201,  273,    0,  273,    0,  273,  194,  201,  201,
      201,  201,  201,  201,  201,  201,  224,  202,  194,  202,
      225,  229,  227,  228,  230,    0,  231,  202,  202,  202,
      202,  202,  202,  202,  202,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  234,  236,  237,  238,  229,
      239,  240,  230,  231,  279,  274,  280,  274,  260,  274,
      275,  276,  275,  276,  275,  276,  277,  215,  277,  278,
      277,  278,  234,  278,  236,  237,  238,  239,  260,  240,
      282,  294,  279,  293,  280,  295,  260,  284,  284,  284,

      284,  284,  284,    0,  215,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  260,  270,  282,  270,  294,
      293,  306,  307,  295,  308,  309,  270,  270,  270,  270,
      270,  270,  270,  270,  310,  311,    0,  218,  297,  297,
      297,  297,  297,  297,  312,    0,  313,  314,  306,  315,
      307,  308,  318,  309,  319,  320,    0,  321,  324,    0,
        0,    0,  310,  311,  218,  328,  329,  328,  329,  328,
      329,    0,  312,  313,  314,    0,  338,  315,  339,  347,
      318,  346,  319,  320,  321,  330,  324,  330,  331,  330,
      331,  332,  331,  332,  333,  332,  333,  334,  333,  334,

      335,  334,  335,  338,  335,  355,  339,  347,  346,  357,
        0,  362,  365,  366,  367,    0,  368,  370,    0,  371,
      373,  374,  375,  376,  377,    0,  378,  379,  380,    0,
      381,  383,  355,  384,  385,  386,  387,  357,  362,  365,
      366,  388,  367,  368,  389,  370,  371,  373,  374,  375,
      376,  390,  377,  378,  379,  391,  380,  381,  383,  392,
      384,  385,  386,  387,  393,  394,  395,  396,  388,  397,
      398,  389,  400,    0,  401,  403,  404,  405,  390,  406,
      407,  409,  391,  410,  412,  413,  415,  392,  416,  417,
      418,  393,  394,  395,  396,  422,  397,  423,  398,  424,

      400,  401,  403,  404,  405,  425,  406,  407,  409,  426,
      410,  412,  413,  415,  427,  416,  417,  418,  431,  433,
      438,    0,  422,    0,  423,    0,  424,    0,    0,    0,
        0,    0,  425,    0,    0,    0,  426,    0,    0,    0,
        0,  427,    0,    0,    0,  431,  433,  438,  446,  446,
      446,  447,    0,  447,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "fcml_intel_lexer.l"
/*
* FCML - Free Code Manipulation Library.
* Copyright (C) 2010-2014 Slawomir Wojtasiak
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.
*
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#line 21 "fcml_intel_lexer.l"
    #include <stdio.h>
    #include <stdlib.h>
    
    #include "fcml_common_lex.h"
    #include "fcml_intel_parser_def.h"
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#line 49 "fcml_intel_lexer.l"
    #define FCML_FM_SIZE_OPERAND(x)                 { yylval->size_operator.size = x; yylval->size_operator.multimedia = FCML_FALSE; return FCML_TK_SIZE_OPERATOR;  }
    #define FCML_FM_MULTIMEDIA_SIZE_OPERAND(x)        { yylval->size_operator.size = x; yylval->size_operator.multimedia = FCML_TRUE; return FCML_TK_SIZE_OPERATOR; }
/*White spaces.*/
#line 839 "fcml_intel_lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE struct fcml_st_parser_data *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int intel_lex_init (yyscan_t* scanner);

int intel_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int intel_lex_destroy (yyscan_t yyscanner );

int intel_get_debug (yyscan_t yyscanner );

void intel_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE intel_get_extra (yyscan_t yyscanner );

void intel_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *intel_get_in (yyscan_t yyscanner );

void intel_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *intel_get_out (yyscan_t yyscanner );

void intel_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t intel_get_leng (yyscan_t yyscanner );

char *intel_get_text (yyscan_t yyscanner );

int intel_get_lineno (yyscan_t yyscanner );

void intel_set_lineno (int line_number ,yyscan_t yyscanner );

int intel_get_column  (yyscan_t yyscanner );

void intel_set_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * intel_get_lval (yyscan_t yyscanner );

void intel_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int intel_wrap (yyscan_t yyscanner );
#else
extern int intel_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int intel_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int intel_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			intel_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				intel__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		intel__load_buffer_state(yyscanner );
		}

	{
#line 57 "fcml_intel_lexer.l"


 /* Decimal integers. */
#line 1105 "fcml_intel_lexer.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 446 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 445 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "fcml_intel_lexer.l"
{ fcml_fn_pu_parse_integer( yytext, &(yylval->integer_value), 10 ); return FCML_TK_INTEGER; }
	YY_BREAK
/* HEX integers. */
case 2:
#line 64 "fcml_intel_lexer.l"
case 3:
#line 65 "fcml_intel_lexer.l"
case 4:
YY_RULE_SETUP
#line 65 "fcml_intel_lexer.l"
{ fcml_fn_pu_parse_integer( yytext, &(yylval->integer_value), 16 ); return FCML_TK_INTEGER; }
	YY_BREAK
/* Floating-points in IEEE 754.
 Floats are not supported yet.
([0-9]*\.[0-9]+|[0-9]+\.)(e[-+]?[0-9]+)?f? |
[0-9]+(e[-+]?[0-9]+)f?    { fcml_fn_pu_parse_float( yytext, &(yylval->float_value) ); return FCML_TK_FLOAT; }
 */
/* GPR. */
case 5:
YY_RULE_SETUP
#line 74 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_AL)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 75 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_CL)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_DL)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_BL)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_AH)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_CH)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_DH)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_BH)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R8L)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R9L)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R10L)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R11L)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R12L)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R13L)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R14L)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 89 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_REG(FCML_REG_R15L)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_X_REG(FCML_REG_SPL)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_X_REG(FCML_REG_BPL)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_X_REG(FCML_REG_SIL)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "fcml_intel_lexer.l"
FCML_FM_GPRS_8_X_REG(FCML_REG_DIL)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_AX)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_CX)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_DX)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_BX)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_SP)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_BP)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 102 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_SI)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_DI)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R8W)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R9W)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R10W)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R11W)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R12W)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R13W)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R14W)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "fcml_intel_lexer.l"
FCML_FM_GPRS_16_REG(FCML_REG_R15W)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_EAX)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_ECX)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_EDX)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_EBX)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_ESP)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_EBP)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_ESI)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_EDI)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 121 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R8D)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 122 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R9D)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R10D)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R11D)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R12D)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R13D)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R14D)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "fcml_intel_lexer.l"
FCML_FM_GPRS_32_REG(FCML_REG_R15D)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 130 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RAX)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 131 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RCX)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 132 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RDX)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 133 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RBX)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 134 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RSP)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 135 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RBP)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 136 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RSI)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 137 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_RDI)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 138 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R8)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 139 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R9)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 140 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R10)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 141 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R11)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 142 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R12)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 143 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R13)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 144 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R14)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 145 "fcml_intel_lexer.l"
FCML_FM_GPRS_64_REG(FCML_REG_R15)
	YY_BREAK
/* SIMD-MMX */
case 73:
YY_RULE_SETUP
#line 148 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM0)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 149 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM1)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 150 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM2)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 151 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM3)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 152 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM4)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 153 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM5)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 154 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM6)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 155 "fcml_intel_lexer.l"
FCML_FM_SIMD_64_REG(FCML_REG_MM7)
	YY_BREAK
/* SIMD-XMM */
case 81:
YY_RULE_SETUP
#line 158 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM0)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 159 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM1)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 160 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM2)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 161 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM3)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 162 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM4)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 163 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM5)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 164 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM6)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 165 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM7)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 166 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM8)
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 167 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM9)
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 168 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM10)
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 169 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM11)
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 170 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM12)
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 171 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM13)
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 172 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM14)
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 173 "fcml_intel_lexer.l"
FCML_FM_SIMD_128_REG(FCML_REG_XMM15)
	YY_BREAK
/* SIMD-YMM */
case 97:
YY_RULE_SETUP
#line 176 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM0)
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 177 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM1)
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 178 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM2)
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 179 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM3)
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 180 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM4)
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 181 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM5)
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 182 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM6)
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 183 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM7)
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 184 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM8)
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 185 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM9)
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 186 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM10)
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 187 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM11)
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 188 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM12)
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 189 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM13)
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 190 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM14)
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 191 "fcml_intel_lexer.l"
FCML_FM_SIMD_256_REG(FCML_REG_YMM15)
	YY_BREAK
/* FPU */
case 113:
YY_RULE_SETUP
#line 194 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST0)                
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 195 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST1)
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 196 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST2)
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 197 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST3)
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 198 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST4)
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 199 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST5)
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 200 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST6)
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 201 "fcml_intel_lexer.l"
FCML_FM_FPU_REG(FCML_REG_ST7)
	YY_BREAK
/* Control registers. */
case 121:
YY_RULE_SETUP
#line 204 "fcml_intel_lexer.l"
FCML_FM_CR_REG(FCML_REG_CR0)
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 205 "fcml_intel_lexer.l"
FCML_FM_CR_REG(FCML_REG_CR2)
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 206 "fcml_intel_lexer.l"
FCML_FM_CR_REG(FCML_REG_CR3)
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 207 "fcml_intel_lexer.l"
FCML_FM_CR_REG(FCML_REG_CR4)
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 208 "fcml_intel_lexer.l"
FCML_FM_CR_REG(FCML_REG_CR8)
	YY_BREAK
/* Debug registers. */
case 126:
YY_RULE_SETUP
#line 211 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR0)
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 212 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR1)
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 213 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR2)
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 214 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR3)
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 215 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR4)
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 216 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR5)
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 217 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR6)
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 218 "fcml_intel_lexer.l"
FCML_FM_DR_REG(FCML_REG_DR7)
	YY_BREAK
/* Segment registers. */
case 134:
YY_RULE_SETUP
#line 221 "fcml_intel_lexer.l"
FCML_FM_SEG_REG(FCML_REG_ES)
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 222 "fcml_intel_lexer.l"
FCML_FM_SEG_REG(FCML_REG_CS)
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 223 "fcml_intel_lexer.l"
FCML_FM_SEG_REG(FCML_REG_SS)
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 224 "fcml_intel_lexer.l"
FCML_FM_SEG_REG(FCML_REG_DS)
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 225 "fcml_intel_lexer.l"
FCML_FM_SEG_REG(FCML_REG_FS)
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 226 "fcml_intel_lexer.l"
FCML_FM_SEG_REG(FCML_REG_GS)
	YY_BREAK
/* RIP */
case 140:
YY_RULE_SETUP
#line 229 "fcml_intel_lexer.l"
FCML_FM_RIP
	YY_BREAK
/* Size operators. */
case 141:
YY_RULE_SETUP
#line 232 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 8 )
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 233 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 16 )
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 234 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 32 )
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 235 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 48 )
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 236 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 64 )
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 237 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 80 )
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 238 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 128 )
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 239 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 256 )
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 240 "fcml_intel_lexer.l"
FCML_FM_MULTIMEDIA_SIZE_OPERAND( 64 )
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 241 "fcml_intel_lexer.l"
FCML_FM_MULTIMEDIA_SIZE_OPERAND( 128 )
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 242 "fcml_intel_lexer.l"
FCML_FM_MULTIMEDIA_SIZE_OPERAND( 256 )
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 243 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 14 * 8 )
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 244 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 28 * 8 )
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 245 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 94 * 8 )
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 246 "fcml_intel_lexer.l"
FCML_FM_SIZE_OPERAND( 108 * 8 )
	YY_BREAK
/* Prefixes */
case 156:
YY_RULE_SETUP
#line 250 "fcml_intel_lexer.l"
{
                    yylval->prefixes = FCML_PREFIX_LOCK;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 255 "fcml_intel_lexer.l"
{
                    yylval->prefixes = FCML_PREFIX_REPNE;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 260 "fcml_intel_lexer.l"
{
                    yylval->prefixes = FCML_PREFIX_REPE;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 265 "fcml_intel_lexer.l"
{
                    yylval->prefixes = FCML_PREFIX_XACQUIRE;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 270 "fcml_intel_lexer.l"
{
                    yylval->prefixes = FCML_PREFIX_XRELEASE;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 275 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_PREFIX_BRANCH_HINT;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 280 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_PREFIX_NOBRANCH_HINT;
                    return FCML_TK_PREFIX;
                }
	YY_BREAK
/* Hints */
case 163:
YY_RULE_SETUP
#line 287 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_HINT_FAR_POINTER;
                    return FCML_TK_HINTS;
                } 
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 292 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_HINT_NEAR_POINTER;
                    return FCML_TK_HINTS;
                }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 297 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_HINT_LONG_FORM_POINTER;
                    return FCML_TK_HINTS;
                }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 302 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_HINT_INDIRECT_POINTER;
                    return FCML_TK_HINTS;
                }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 307 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_HINT_DIRECT_POINTER;
                    return FCML_TK_HINTS;
                }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 312 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_OP_HINT_RELATIVE_ADDRESSING;
                    return FCML_TK_EAO_HINTS;
                }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 317 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_OP_HINT_ABSOLUTE_ADDRESSING;
                    return FCML_TK_EAO_HINTS;
                }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 322 "fcml_intel_lexer.l"
{
                    yylval->hints = FCML_OP_HINT_SIB_ENCODING;
                    return FCML_TK_SIB_HINT;
                }
	YY_BREAK
/* Identifiers. */
case 171:
YY_RULE_SETUP
#line 328 "fcml_intel_lexer.l"
{
                    yylval->symbol.text = (fcml_string)yytext;
                    yylval->symbol.length = (fcml_usize)yyleng;
                    return FCML_TK_SYMBOL; 
                }
	YY_BREAK
/* Operators and parentheses. */
case 172:
YY_RULE_SETUP
#line 335 "fcml_intel_lexer.l"
{ return ','; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 336 "fcml_intel_lexer.l"
{ return '+'; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 337 "fcml_intel_lexer.l"
{ return '-'; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 338 "fcml_intel_lexer.l"
{ return '*'; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 339 "fcml_intel_lexer.l"
{ return '/'; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 340 "fcml_intel_lexer.l"
{ return '['; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 341 "fcml_intel_lexer.l"
{ return ']'; }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 342 "fcml_intel_lexer.l"
{ return '('; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 343 "fcml_intel_lexer.l"
{ return ')'; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 344 "fcml_intel_lexer.l"
{ return ':'; }
	YY_BREAK
/* Ignore white spaces. */
case 182:
YY_RULE_SETUP
#line 347 "fcml_intel_lexer.l"

	YY_BREAK
/* Anything else is not expected. */
case 183:
YY_RULE_SETUP
#line 350 "fcml_intel_lexer.l"
{ return FCML_TK_UNEXPECTED; }
	YY_BREAK
/* Ignore like white spaces. */
case 184:
/* rule 184 can match eol */
YY_RULE_SETUP
#line 353 "fcml_intel_lexer.l"

	YY_BREAK
case 185:
YY_RULE_SETUP
#line 355 "fcml_intel_lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2150 "fcml_intel_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * intel_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( intel_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of intel_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					intel_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			intel_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) intel_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 446 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 446 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 445);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					intel_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( intel_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void intel_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        intel_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            intel__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	intel__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	intel__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void intel__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		intel_pop_buffer_state();
	 *		intel_push_buffer_state(new_buffer);
     */
	intel_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	intel__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (intel_wrap()) processing, but the only time this flag
	 * is looked at is after intel_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void intel__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE intel__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) intel_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in intel__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) intel_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in intel__create_buffer()" );

	b->yy_is_our_buffer = 1;

	intel__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with intel__create_buffer()
 * @param yyscanner The scanner object.
 */
    void intel__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		intel_free((void *) b->yy_ch_buf ,yyscanner );

	intel_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a intel_restart() or at EOF.
 */
    static void intel__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	intel__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then intel__init_buffer was _probably_
     * called from intel_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void intel__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		intel__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void intel_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	intel_ensure_buffer_stack(yyscanner);

	/* This block is copied from intel__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from intel__switch_to_buffer. */
	intel__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void intel_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	intel__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		intel__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void intel_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)intel_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in intel_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)intel_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in intel_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE intel__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) intel_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in intel__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	intel__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to intel_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       intel__scan_bytes() instead.
 */
YY_BUFFER_STATE intel__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return intel__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to intel_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE intel__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) intel_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in intel__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = intel__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in intel__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE intel_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int intel_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int intel_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *intel_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *intel_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t intel_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *intel_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void intel_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void intel_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "intel_set_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void intel_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "intel_set_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see intel__switch_to_buffer
 */
void intel_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void intel_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int intel_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void intel_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * intel_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void intel_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* intel_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int intel_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) intel_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* intel_lex_init_extra has the same functionality as intel_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to intel_alloc in
 * the yyextra field.
 */

int intel_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    intel_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) intel_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    intel_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from intel_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * intel_lex_init()
     */
    return 0;
}

/* intel_lex_destroy is for both reentrant and non-reentrant scanners. */
int intel_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		intel__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		intel_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	intel_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        intel_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * intel_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    intel_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 355 "fcml_intel_lexer.l"




